### ISSUE TITLE
About us - H2 intro line height

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#10]
**Describe the bug**
Font size and line height is different to the design.

**Expected behavior**
Please can we make it font size: 40px and line height 54 px?

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**
<img width="1026" alt="Screenshot 2020-02-21 at 14 43 48" src="https://user-images.githubusercontent.com/61156618/75043850-96dcf480-54b8-11ea-9c38-2f26bd3b3342.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.2
 - Browser [e.g. chrome, safari] Chrome

**Comment by scott-psycle** [comment]
This should be fixed in the next release.
