### ISSUE TITLE
Button interaction speed

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#11]
**Is your feature request related to a problem? Please describe.**
Button interactions are slower than reference animations

**Describe the solution you'd like**
Can we speed up the animation to more closely reflect this animation:

https://drive.google.com/file/d/1GfM_tecDxDw5yWvreR58fulZOLXyF7jS/view?usp=sharing

**Priority**
- High (keeping you from completing day-to-day tasks)

**Ideal deadline**
Phase 1 launch

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.

**Comment by Sean-opx** [comment]
Looks good
