### ISSUE TITLE
Changes to the People page

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#110]
- [x] Do not display the role field
- [x] Truncate the bio text after 600 chars with a "More" that expands 
- [ ] Add a rich-text stream field for us to include in the page (so we can briefly add a description under each type of person)
- [x] Ability to link to the individual people title headers, ie https://www.reset.tech/people#network-investment-council

**Comment by frjo** [comment]
@danblah  Does not https://github.com/ResetNetwork/apply-app/issues/101 take care of number 3? Already have an PR for that at https://github.com/ResetNetwork/apply-app/pull/109. There I add a plaintext field. IS rich text really needed for a brief description?

**Comment by danblah** [comment]
Oh yes, to #101. Sorry for the dup.
