### ISSUE TITLE
Homepage - resources module

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#12]
**Describe the solution you'd like**
Looking at these modules again they feel a little flat in comparison to the other interactions on the site. Is there any way we can add a zoom to the image on hover like you did on Tharsus: 

https://www.tharsus.co.uk/our-thinking

**Priority**
- Low priority (annoying, would be nice to not see)

**Ideal deadline**
Phase 1 launch if possible, if not phase 2 is fine.

**Comment by danblah** [comment]
i really like @Sean-opx's suggestion there.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.

**Comment by Sean-opx** [comment]
Nice
