### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#13]
**Describe the bug**
Mobile navigation is different to the design

**Expected behavior**
Can we match to the original designs?

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**
![IMG_0143](https://user-images.githubusercontent.com/61156618/75045933-128c7080-54bc-11ea-945c-ca3bb7a5d60a.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  iPhone 8
 - OS: [e.g. iOS8.1] 13.3.1
 - Browser [e.g. stock browser, safari] Safari

**Additional context**

**Comment by scott-psycle** [comment]
This will be addressed in the next release.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.

**Comment by Sean-opx** [comment]
Thanks Scott, looking good
