### ISSUE TITLE
Mobile H2's

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#14]
**Describe the bug**
Size of all the H2's that sit underneath the intro text are a larger type size

**Expected behavior**
Please can we make H2's consistent across mobile

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**
![IMG_0144](https://user-images.githubusercontent.com/61156618/75046160-8595e700-54bc-11ea-80bd-e257132890cb.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone8
 - OS: [e.g. iOS8.1] 13.3.1
 - Browser [e.g. stock browser, safari] Chrome

**Comment by scott-psycle** [comment]
This will be addressed in the next release.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
