### ISSUE TITLE
Open calls: Where did all the streamfields blocks go?

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#15]
I'm used to the Request page type that had all the other formatting options. I'm thinking about how we list reviewers, related projects, etc down the road.

**Comment by scott-psycle** [comment]
@danblah @Sean-opx I can see on the OTF pages like this:  

https://www.opentech.fund/funds/digital-integrity-fellowship/

You've used the streamfields to build the page.  The streamfields you have on the back end are:

- Heading
- Paragraph
- Box
- Apply Link
- Image
- Quote
- Embed
- Call to Action
- Document
- List of Projects Funded (we don't have 'Projects' entities in the Reset site 
- List of Reviewers

If we need to implement these on the fund page we'll need a design for the layout and also I'll have to provide a quote for the development effort.
