### ISSUE TITLE
Open calls: Reuse the Title and Text fields for card fields?

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#16]
I'm not sure I understand the purpose of Card title and Card text? It seems duplicative of the page title and Content > text. See https://test-apply.reset.tech/admin/pages/18/edit/

**Comment by scott-psycle** [comment]
We could just use the title and the text, however, separating out the card content gives you more flexibility to use slightly different text on the Open Calls page.

**Comment by danblah** [comment]
All good as is for me. Thanks!
