### ISSUE TITLE
Add reset logo to site settings in wagtail admin

### ISSUE THREAD

**Issue by frjo** [ResetNetwork/apply-app#19]
https://test-apply.reset.tech/admin/settings/utils/systemmessagessettings/2/

This will replace the OTF logo on the apply site.

**Comment by scott-psycle** [comment]
@frjo I've added the Reset logo, but it's still showing the OTF logo.  Any ideas?

**Comment by frjo** [comment]
My bad, somehow I have missed to add the needed code to `base-apply.html`, it only exist on `base.html`. I will fix that and then the logo you added will show up.
