### ISSUE TITLE
Convert PNG photos to JPEG to make them a lot smaller

### ISSUE THREAD

**Issue by frjo** [ResetNetwork/apply-app#20]
The from page weigh in at 2,5 MB now, could we convert the photos that now are in PNG to JPEG? 

Examples <https://test-apply.reset.tech/admin/images/6/> and <https://test-apply.reset.tech/admin/images/19/>

I think we can shave at least 1 MB of the from page with this alone.

**Comment by scott-psycle** [comment]
@Sean-opx @danblah This is content related.  When adding images can you use JPEGs instead of PNGs?

**Comment by Sean-opx** [comment]
Hi Scott

No problem, we will do this when we upload the final content next week.

All the best,
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx @frjo I assume this has been completed now.  Please can you close if there's nothing more to be done.

**Comment by Sean-opx** [comment]
Hi Scott this has been completed. Having some trouble closing this thread - I wondering if it's because it was set up by Fredrik?
