### ISSUE TITLE
Logo change

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#22]
**Is your feature request related to an existing functionality? Please describe.**
Please can we change the 'Project Alpha' logo to the Reset logo. White and black versions can be downloaded below:

https://we.tl/t-ejaYQ6BfON

**Priority**
- High (keeping you from completing day-to-day tasks)

**Ideal deadline**
Phase 1 launch

**Comment by scott-psycle** [comment]
@Sean-opx Do you just mean in the top left of the site?

**Comment by Sean-opx** [comment]
Yes please.

**Comment by scott-psycle** [comment]
@Sean-opx This is done now.  Could you close if you're happy.
