### ISSUE TITLE
Desktop - navigation

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#24]
**Describe the bug**
– When highlighted the text style should be Bold (not regular)
– Current page should be highlighted

**Comment by Sean-opx** [comment]
– Blue box appears around the cross/close button. (iPhone 7 Safari)

![IMG_5150](https://user-images.githubusercontent.com/61156618/75688676-d0231a80-5c97-11ea-880a-4c3ca06fff90.PNG)

**Comment by Sean-opx** [comment]
**Menu item highlight**
– Please highlight current page (Bold)

**Comment by Sean-opx** [comment]
– Can you reduce the spacing between the page name and divider line above it to 10px

**Comment by frjo** [comment]
On desktop the main navigation is overlapping the carousel unless you have a really wide window.

Several of the carousel images has a light backrund making the light grey meny text hard to read.

**Comment by scott-psycle** [comment]
@Sean-opx Thoughts on Fredriks comments?

**Comment by scott-psycle** [comment]
Initially you can't, unless you're on a wider screen.  As you scroll down the logo animates and the header carousel reduces in size.  We'll hit the same issue as you scroll down the page where the menu is over an image.  

Needs input from @Sean-opx .

**Comment by scott-psycle** [comment]
@danblah Could you open a separate issue for this menu visibility please.  The original issue with the menu items being highlighted will be fixed in the candidate release.

**Comment by Sean-opx** [comment]
Migrated the conversation to new thread on Github and left some feedback.
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
