### ISSUE TITLE
Homepage - Top carousel 

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#25]
**Describe the bug**
– Looks like it’s off centre when it’s large
– When small it doesn’t align to the columns below (shown below)

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**
![Caroousel_Position](https://user-images.githubusercontent.com/61156618/75687695-137c8980-5c96-11ea-934f-2f3a362bd248.jpg)

**Comment by scott-psycle** [comment]
@Sean-opx We've been able to address the alignment of the header carousel with the text.  The 

Regarding the centring of the header, altering the layout at this stage is going to be a significant job.  Potentially something we can look at in a future release.
