### ISSUE TITLE
Homepage - Open calls section

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#27]
**Describe the bug**
– Scroll jacking – snaps to a strange position leaving no space above the content (shown below)

**Screenshots**
<img width="1537" alt="Screenshot 2020-03-02 at 11 32 17" src="https://user-images.githubusercontent.com/61156618/75687892-6a825e80-5c96-11ea-9a01-50caf8cfc8a4.png">

**Comment by scott-psycle** [comment]
@Sean-opx Ongoing discussion with Luminate about whether the scroll jacking will be removed.

**Comment by scott-psycle** [comment]
We can look at adjusting the padding at the top of the Open Calls section when we address the spacing between modules.

**Comment by scott-psycle** [comment]
Scroll jacking has been removed.
