### ISSUE TITLE
People - bio images

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#30]
**Describe the bug**
– Can the images be offset 50–100px to the right of the cursor? Feels like this will make it more user friendly if the cursor isn’t centred over the image.

**Comment by scott-psycle** [comment]
On hold until decided whether the hover images will be removed in favour of a new layout.

**Comment by scott-psycle** [comment]
@Sean-opx We've now offset the people images so that they track with the cursor, but the cursor is anchored to the bottom left of the image.

![image](https://user-images.githubusercontent.com/41118956/75897763-fd570080-5e30-11ea-9ba1-47c5aeb2da0a.png)

**Comment by Sean-opx** [comment]
Hi Scott

That looks better - can we see in the next update?

Thanks,
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
Yes, this will be in the candidate release tomorrow.

**Comment by scott-psycle** [comment]
@Sean-opx @danblah Do we need a new design layout, or is the current layout ok?

**Comment by Sean-opx** [comment]
Sorry Scott, still awaiting sign off on the new design before we hand over assets. Will give Sian another nudge now.

**Comment by Sean-opx** [comment]
Hi Scott

Revised people module design has been signed off. See below assets:

https://invis.io/DGWJO7TEHJ3

Any questions, just let me know.

All the best,

**Comment by scott-psycle** [comment]
This is now complete and on Live.  Closing.
