### ISSUE TITLE
Login - dark grey background

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#31]
**Describe the solution you'd like**
– Can this fade in like the other elements?

**Comment by scott-psycle** [comment]
@Sean-opx The whole page is the same colour.  I'm not sure what you mean here.

**Comment by Sean-opx** [comment]
Ignore this comment, we were looking at an older version of the log in page. Incidentally is it possible to add the reset typeface to this [area](https://test-apply.reset.tech/dashboard/)?

**Comment by scott-psycle** [comment]
@Sean-opx Changes to the dashboard are outside of the scope of this phase of the project.  I dare say they may come in a future phase though.

**Comment by Sean-opx** [comment]
No worries, thanks for letting me know.
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx Are you happy to close this issue?
