### ISSUE TITLE
Mobile - type sizes

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#32]
**Describe the bug**
– Inconsistent body copy sizes. Feels small on the homepage and about page but then on the People page it seems correct. Can the body size throughout be changed to match the People page bios? 

**Expected behavior**
Can the body size throughout be changed to match the People page bios? 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
