### ISSUE TITLE
Mobile - about - intro paragraph

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#34]
**Describe the bug**
– Can this be reduced in size? Maybe to the next H level? Feels very large

**Comment by scott-psycle** [comment]
@Sean-opx On review, it doesn't match the designs.  It's currently 30px, but designs are 20px.  We'll reduce to match the designs.

**Comment by scott-psycle** [comment]
@Sean-opx Or would you prefer 24px?

![image](https://user-images.githubusercontent.com/41118956/75799740-63c81a00-5d70-11ea-8806-fd4143f954a6.png)

**Comment by Sean-opx** [comment]
Thanks Scott, 24px is our preferred.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
