### ISSUE TITLE
Open call - finding detail page

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#35]
**Describe the bug**
– Button style isn't correct. Button default state should be white text on black background.
– There is also a white key line around the clicked yellow state

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**
<img width="963" alt="Screenshot 2020-03-02 at 17 54 38" src="https://user-images.githubusercontent.com/61156618/75703923-521f3d80-5cb0-11ea-9b91-3d77f5c76a59.png">

**Comment by scott-psycle** [comment]
This styling will be in the candidate release.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
