### ISSUE TITLE
Open call - form

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#37]
**Describe the bug**
– Please can you remove the dash bullet points
– Lists are currently single column with circular clickers - these need to be two column with square clickers. See original design below:

<img width="722" alt="Screenshot 2020-03-02 at 18 07 57" src="https://user-images.githubusercontent.com/61156618/75704243-e689a000-5cb0-11ea-992c-e0b95e043a22.png">

**Comment by scott-psycle** [comment]
@Sean-opx What do you mean by the dash bullet points?  Can you provide a screenshot please?

The styling of the checkboxes will be in the next sprint release, targeted for the 24th March phase 2 launch.

**Comment by Sean-opx** [comment]
Hi Scott

Currently having trouble getting into the CMS but we were seeing m dashes before some of the text in the form. This may just be a content issue as opposed to a bug, but thought we'd flag.

**Comment by scott-psycle** [comment]
I see it now.  Those will be removed in the next sprint.  We're still working on the Open Calls pages, so some styling is to be applied.

**Comment by scott-psycle** [comment]
@Sean-opx The final styling has now been applied to the form.  Please retest.

**Comment by Sean-opx** [comment]
Hi Scott. Columns are fixed, but the clickers are still circular. Please can these be square?

<img width="770" alt="Screenshot 2020-03-13 at 13 44 57" src="https://user-images.githubusercontent.com/61156618/76626584-51e53480-6531-11ea-9e60-f65b1b80d392.png">

**Comment by scott-psycle** [comment]
I'm afraid not in Wagtail.  Those are single select radio buttons.  Radio buttons have to be round.  The checkboxes are square.

**Comment by Sean-opx** [comment]
No worries thanks for clarifying.
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx Can this be closed?
