### ISSUE TITLE
Open calls - footer

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#38]
**Describe the bug**
Footer is different colour to page background. Can these match please?

<img width="1737" alt="Screenshot 2020-03-02 at 18 10 13" src="https://user-images.githubusercontent.com/61156618/75704367-2a7ca500-5cb1-11ea-8b7b-34b6fe3acab3.png">

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.
