### ISSUE TITLE
Logo animation doesn't go away

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#42]
on desktop, with chrome, if you scroll down before animation gets a chance to go away, it just sticks over everything. see screen shot.
![Screenshot 2020-03-04 at 10 51 12](https://user-images.githubusercontent.com/620336/75897237-42b20880-5e06-11ea-8ad9-71090d4e008e.png)

**Comment by scott-psycle** [comment]
@danblah This is fixed in the candidate release.
