### ISSUE TITLE
Desktop - animation overlap with nav

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#44]
Hi Scott

Please can we reduce the size of the animation by 10% to reduce the amount of overlap with the navigation? 

There is currently no space to the left and right of the animation when you land on the page on a smaller browser window. Can we add some padding either side so that it's closer to the original design?

https://invis.io/56VV3KAWZST#/403826891_COOKIE_NOTIFICATION

Thanks,

**Comment by scott-psycle** [comment]
@Sean-opx Should we try to keep the hero image carousel (on initial load) clear of the navigation at all widths if possible?

**Comment by Sean-opx** [comment]
@scott-psycle  Not necessarily. We think it's visually quite nice when the carousel overlaps with the nav slightly, but we wouldn't recommend it overlapping any further than say than the last 'e' at the end of 'People' at its tightest. Hope that all makes sense - any questions, just let me know.

**Comment by scott-psycle** [comment]
@Sean-opx This is slightly more complex than I'd thought, so I'll add it as an issue to pick up post launch.  However, as an alternative could we consider hiding the nav initially and having it fade in with the intro animation?

Dan has also suggested in this issue (https://github.com/ResetNetwork/apply-app/issues/43) auto scrolling the user if they don't do anything for 3 seconds.  Could we be back to auto triggering the animation after a few seconds?

**Comment by Sean-opx** [comment]
Hi Scott

OK no problem. If we hide the nav initially, it might not be very user friendly for people who arrive at the site and want to dive straight into the page.

Happy to go with Dan's suggestion about triggering the animation after a few seconds.

Thanks,

**Comment by scott-psycle** [comment]
@Sean-opx We've now implemented the auto animate on the header if there's no movement after 3 seconds.

**Comment by Sean-opx** [comment]
Looks good to me. Shall we keep this issue open for the wider animation/nav spacing discussion?

**Comment by scott-psycle** [comment]
Now that users will see the overlap for a maximum of 3 seconds, is there still an issue?

**Comment by Sean-opx** [comment]
I think it works as a good short term solution, but visually it feels very overwhelming when there is no space to the left and right of the animation when you land on the page on a smaller browser window.  If we can add it to the list of items to address post launch that would be great.
