### ISSUE TITLE
People snippets

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#47]
– Can we add hyperlink functionality to the 'About' field in the people bios
– Can we make the 'role' field optional in the people bios

**Comment by scott-psycle** [comment]
@Sean-opx We'll need to update the about field to use the rich text editor, rather than the plain text field.

This will give the admin user the ability to format the text, but all styles will be ignored on the front end, and will just be displayed as a paragraph text.

The role field will be made optional in the next release.

**Comment by Sean-opx** [comment]
Sounds good!
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx This has been implemented in the latest release.  Please close if you're happy.

**Comment by Sean-opx** [comment]
Hi Scott

Rich text editor is working on test. Is it possible to add bold and italic styles into this field?

Thanks,

**Comment by scott-psycle** [comment]
@Sean-opx We can.  Are there any other styles that you want added, or just those two?

**Comment by Sean-opx** [comment]
Hi Scott, bold and italic should cover all the styles we need.

Cheers,
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
This is now complete.  Closing.
