### ISSUE TITLE
Add a Credit link to the footer

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#48]
That links to https://www.reset.tech/credit

so it looks like on desktop: 

Data & privacy policy | Term of use | Credits

**Comment by scott-psycle** [comment]
@danblah You can do that in the Settings menu.  There's a Footer settings page.  You'll need to add the footer menu item to both the main site and the apply site, choosing the site in the top right.

![image](https://user-images.githubusercontent.com/41118956/76431511-8e862400-63a9-11ea-8f05-3cd39e7870fe.png)

**Comment by scott-psycle** [comment]
@Sean-opx Could you add this to the Live site please.  The page exists, it just needs to be added to the footer.

**Comment by Sean-opx** [comment]
No problem, that's been updated

**Comment by scott-psycle** [comment]
@Sean-opx I can see it on the apply site, but you'll need to add it to the main site too.  See my comment a few above.  You need to change the URL in the top right of the settings page.

**Comment by Sean-opx** [comment]
That's strange I added them to both on the back end - see screenshots below. Let me know if I'm doing anything wrong.

[Wagtail   Editing Reset Network Footer Menu   ResetNetworkMenusFooter object  1 .pdf](https://github.com/ResetNetwork/apply-app/files/4329403/Wagtail.Editing.Reset.Network.Footer.Menu.ResetNetworkMenusFooter.object.1.pdf)
[Wagtail   Editing Reset Network Footer Menu   ResetNetworkMenusFooter object  2 .pdf](https://github.com/ResetNetwork/apply-app/files/4329404/Wagtail.Editing.Reset.Network.Footer.Menu.ResetNetworkMenusFooter.object.2.pdf)

**Comment by scott-psycle** [comment]
Investigating this.  It could be a caching issue.

**Comment by scott-psycle** [comment]
This is complete now.  Looks like it was just a caching issue.  Closing.
