### ISSUE TITLE
Homepage banner transition

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#5]
**Describe the bug**
Homepage logo deconstruction animation is triggering on page load

**Expected behavior**
The logo should appear on page load and deconstructions when the users scrolls down from the homepage banner. See ref below:

https://drive.google.com/file/d/1NAMWYUbAY7F07jHZR9HFXMIQB12UfwwN/view?usp=sharing

**Priority**
- High (keeping you from completing day-to-day tasks)

**Screenshots**

<img width="1662" alt="Screenshot 2020-02-21 at 12 26 37" src="https://user-images.githubusercontent.com/61156618/75042715-c68afd00-54b6-11ea-9818-154d916f8a28.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.2
 - Browser [e.g. chrome, safari] Chrome

**Comment by Sean-opx** [comment]
Mobile transition seems to be broken. It should follow the same principle as the desktop version

**Comment by Sean-opx** [comment]
Transition is working on desktop nicely. Can this be removed on mobile? The graphic elements don’t appear in the corners so this doesn’t need to appear here.

**Comment by scott-psycle** [comment]
@Sean-opx If you're now happy with this please can you close?

There is a separate issue for auto triggering the animation after 3 seconds.
