### ISSUE TITLE
Sharing the site on social

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#50]
When people have been Tweeting or sending a link to the Reset website, it’s coming up without a picture and saying “reset network” - we definitely want to get rid of ’network’ if possible, and would be great to have a pic (perhaps of the 205 graphic) if there’s a way to do that in the back end?

![Screen Shot 2020-03-11 at 11 44 46 AM](https://user-images.githubusercontent.com/61156618/76414158-b1570f00-638e-11ea-8c45-fb7b688fae68.png)

**Comment by scott-psycle** [comment]
@Sean-opx I believe the 'Promote' tab can be used to add the social image and text.  If you go into edit the homepage you can see the tab.

![image](https://user-images.githubusercontent.com/41118956/76432264-a611dc80-63aa-11ea-93fe-cac43ed2a2a5.png)

Just as a note, this is existing functionality from the OTF site, not something we've added for Reset.

**Comment by Sean-opx** [comment]
Thanks Scott, that looks like it's fixed most of it, however Twitter isn't pulling through the image I've uploaded. Could you take a look for me?

Cheers,

**Comment by scott-psycle** [comment]
The fix for this should be in the next release.  There was an issue with the image file path being duplicated.

**Comment by scott-psycle** [comment]
@Sean-opx We've fixed the image path now.  You can see that it's appearing correctly in the social tags in the head of the page.  Unfortunately you won't be able to test this by sharing to Twitter or Facebook on Test, as the site is behind basic auth.

These are the tags from Test though.

```
<meta name="twitter:card" content="summary">  
<meta name="twitter:site" content="@resetdottech">  
<meta name="twitter:title" content="Reset">  
<meta name="twitter:description" content="">  
<meta name="twitter:image" content="https://test-public.reset.tech/images/Reset_Avatar_400x400_1.width-320.width-320.jpg">  
<meta property="og:type" content="website">  
<meta property="og:url" content="https://test.reset.tech/">  
<meta property="og:title" content="Reset">  
<meta property="og:image" content="https://test-public.reset.tech/images/Reset_Avatar_400x400_1.width-320.width-320.jpg">  
<meta property="og:description" content="">  
<meta property="og:site_name" content="reset">
```

**Comment by Sean-opx** [comment]
Morning Scott

Thanks for looking into this. Will wait for this to go on the live site to test properly, but it sounds like you've fixed it :)

All the best,

**Comment by scott-psycle** [comment]
@Sean-opx Happy to close this?  I'm seeing the correct share image.

![image](https://user-images.githubusercontent.com/41118956/77097665-0affaf00-6a09-11ea-8aca-2f8a0fb62822.png)
