### ISSUE TITLE
Homepage - resource module

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#52]
Hi Scott

I was looking at the spacing on the test site and noticed that the resource module on the homepage has shifted out of alignment with the modules above - see screenshot below:

[Reset Home   Reset.pdf](https://github.com/ResetNetwork/apply-app/files/4329524/Reset.Home.Reset.pdf)

Thanks,

**Comment by scott-psycle** [comment]
@Sean-opx The Resources section takes it's alignment from the right hand edge of the Open Calls section above it, rather than the left hand edge of the Work section.  It's only above 1500px wide that the left hand edge moves out of alignment with the Work section.

**Comment by Sean-opx** [comment]
Hi Scott. Sorry I'm a little confused, it seems to be working fine on the live site (see below) where we're working with the same layout.

[Reset Home   Reset Homepage.pdf](https://github.com/ResetNetwork/apply-app/files/4329826/Reset.Home.Reset.Homepage.pdf)

Do let me know if I'm missing anything.

**Comment by scott-psycle** [comment]
Sorry Sean, I missed that this was a change to the current Live.  We'll get that fixed.

**Comment by Sean-opx** [comment]
Thanks Scott
---


*Sean Croucher**Project Manager*

–
*OPX*

The Timber Yard, 53 Drysdale Street, London N1 6ND
Registered Office. OPX Ltd, Company no 06289138, Registered in England, VAT
no 657 5539 94.

T: +44 (0)20 7729 6295
opx.studio
Follow us on Instagram <https://www.instagram.com/opx.studio>, Medium
<https://medium.com/@OPX_London>, and Tumblr <https://opxstudio.tumblr.com/>

**Comment by scott-psycle** [comment]
@Sean-opx This is fixed in the release on staging.  Could you have a look and close this issue if you're happy.
