### ISSUE TITLE
Homepage banner - animation speed

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#6]
**Describe the bug**
Homepage banner animation transition slows down in its reduced state. 

**Expected behavior**
It should be running at the same speed as the animation that appears on page load

**Priority**
- High (keeping you from completing day-to-day tasks)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.2
 - Browser [e.g. chrome, safari] Chrome

**Comment by scott-psycle** [comment]
@Sean-opx What should the delay be between images?  The example here shows a fast transition between images.  I assume it shouldn't be that fast?

https://drive.google.com/file/d/1NAMWYUbAY7F07jHZR9HFXMIQB12UfwwN/view

**Comment by Sean-opx** [comment]
Hi Scott

Transition speed for the animation when you land on the page is fine. There shouldn't be any delay when it goes down to its reduced state.

Can you speed up the transitions between the images when the animation at the size (below) to match the transition speed of the animation when you land on the page?

<img width="1665" alt="Screenshot 2020-02-26 at 16 49 13" src="https://user-images.githubusercontent.com/61156618/75367253-f3c11c00-58b7-11ea-81a0-0057a87a70c4.png">

Hope that makes sense? Feel free to give a call if anything needs further clarification.

**Comment by scott-psycle** [comment]
No problem, we can do that.

**Comment by frjo** [comment]
Is it really supposed to be as fast as it's now on https://test.reset.tech ? Feels like you need a seizure warning sign ;-).

**Comment by scott-psycle** [comment]
As discussed, we will reduce the transition speed of the images in the reduced size header carousel.

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.

**Comment by Sean-opx** [comment]
Looks good!
