### ISSUE TITLE
Log in page on test is looking a little strange

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#60]
<img width="1744" alt="Screenshot 2020-03-19 at 14 19 49" src="https://user-images.githubusercontent.com/61156618/77078016-ef3adf80-69ed-11ea-8027-852107104655.png">

**Comment by scott-psycle** [comment]
@Sean-opx Clicking the login link should take you to this URL - https://test-apply.reset.tech/login/

I assume that's the basic auth.  You need to login with:

reset
P2xgviuU

**Comment by Sean-opx** [comment]
Ah yes you're right - working now :)
