### ISSUE TITLE
On open-calls page, add a rich-text field for after the listing of open calls, and remove extra space surrounding open calls

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#69]
can we make it more inline with the spacing for other headers? see https://www.reset.tech/open-calls/

**Comment by frjo** [comment]
It looks bad because the header "List of open calls" is added as the last test in the rich text field of the section above the listing. We should add a prober header to the open calls listing and remove the one added in the rich text field.

**Comment by frjo** [comment]
This seems to be a none issue now, the page has changes. Closing.
