### ISSUE TITLE
Homepage - open calls

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#7]
**Describe the bug**
Content has been added for open call module but it’s not showing on the front end?

**Priority**
- High (keeping you from completing day-to-day tasks)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.2
 - Browser [e.g. chrome, safari] Chrome

**Comment by scott-psycle** [comment]
@Sean-opx You need to edit the Open Calls section of the homepage and add the open calls using the button shown below.

![image](https://user-images.githubusercontent.com/41118956/75242572-4d461f80-57c0-11ea-83db-3851e942e2d0.png)

**Comment by Sean-opx** [comment]
Thanks for clarifying Scott.
