### ISSUE TITLE
Add a "More about open calls" link on the front page open calls section

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#72]
At https://apply.reset.tech/admin/pages/5/edit/, see the "CONTENT - SECTION 2 (OPEN CALLS)" section, there is a Link option that is set to go to the https://www.reset.tech/open-calls/. Right now that doesn't seem to render anything.

Make that render a button like the other sections with the inside text "More about open calls"

**Comment by frjo** [comment]
@danblah Fill in the "Link Text" field in section 2 and the link will appear.

It now renders as small text link just to the right of the section header. Looks like this is how the design is ment to look. Let me know if you want to change it to look like the other sections with a button at the end of the section instead.

![open_calls_view_all](https://user-images.githubusercontent.com/191392/78231604-5ae37900-74d3-11ea-83e5-b0bb75acad7b.png)

**Comment by scott-psycle** [comment]
@danblah Can we close this one down now?  As Fredrik mentioned above, you're able to create a link to the Open Calls page using the link text field.

**Comment by frjo** [comment]
Closing this. If we want to change the look on the link as I mentioned in the comment above, please reopen and change the title of the issue.
