### ISSUE TITLE
Check for consent acceptance before being able to submit an application

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/apply-app#81]
We have a data use policy specifically for applicants where an opt-in is required before submitting an application. How best to:
1. Check that the user/applicant has accepted the consent pop up when visiting an application form
2. Give them an option to accept if they have not, only when visiting/reloading an application form
3. Grey out or disable the application form if they've not accepted, stating clearly why and giving them an option to accept
4. Enabling the form when they've accepted.

?

cc @frjo

**Comment by scott-psycle** [comment]
@danblah Doesn't the checkbox at the end of the application form not achieve that goal?  Making the checkbox mandatory means that they can't submit their application without confirming that they accept the data policy.

![image](https://user-images.githubusercontent.com/41118956/80803934-9abd7f00-8bab-11ea-8e89-fdc082d575f7.png)
