### ISSUE TITLE
Body copy - paragraph spacing

### ISSUE THREAD

**Issue by Sean-opx** [ResetNetwork/apply-app#9]
**Is your feature request related to a problem? Please describe.**
The paragraph spacing on the body copy is very large

**Describe the solution you'd like**
Add a space after paragraph of 10

**Additional context**
<img width="421" alt="Screenshot 2020-02-21 at 14 41 45" src="https://user-images.githubusercontent.com/61156618/75043620-4cf40e80-54b8-11ea-847e-89b12bebf475.png">

**Priority**
- Low priority (annoying, would be nice to not see)

**Ideal deadline**
For phase 1 launch

**Comment by Sean-opx** [comment]
Hi Scott

Sorry for the confusion. I was referring to the space between the paragraphs - can we reduce it so that it more closely matches the UI designs? See screenshots from original sketch file attached.

<img width="1119" alt="Screenshot 2020-02-27 at 14 32 45" src="https://user-images.githubusercontent.com/61156618/75454983-41985b80-596e-11ea-877b-017bac6b09fe.png">
<img width="233" alt="Screenshot 2020-02-27 at 14 32 42" src="https://user-images.githubusercontent.com/61156618/75455003-478e3c80-596e-11ea-912e-a947ca7a9155.png">

Feel free to give me a call if I'm still not making sense.

Thanks,

**Comment by Sean-opx** [comment]
– Can a 10px space after be included on all body paragraphs? (This seems to be implemented on the People page bios – match to this)

**Comment by scott-psycle** [comment]
@Sean-opx Please retest and close.

**Comment by Sean-opx** [comment]
Thanks Scott, much better.
